baseURL = "http://chinanf-boy.github.io/goreleaser-zh/"
languageCode = "zh-CN"
title = "GoReleaser & yobrave"
copyright = "Made with ❤️ by GoReleaser contributors."
googleAnalytics = "UA-128555056-1"
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[params]
logo = "https://avatars2.githubusercontent.com/u/24697112?v=3&s=140"
